In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv('/content/Iris.csv')
df

      Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [5]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
features = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
target = ['Species']
x = df[features]
y = df[target]

In [9]:
x.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [10]:
y.head()

       Species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=17, stratify=y)

In [20]:
model = LogisticRegression(max_iter=200)
model.fit(x_train, y_train.values.ravel())
y_predict = model.predict(x_test)
compare = pd.DataFrame({"Actual Species": y_test.values.ravel(),"Predicted Species": y_predict}) # Flatten y_test.values to a 1D array
compare

     Actual Species Predicted Species
0   Iris-versicolor   Iris-versicolor
1   Iris-versicolor   Iris-versicolor
2    Iris-virginica    Iris-virginica
3   Iris-versicolor   Iris-versicolor
4   Iris-versicolor   Iris-versicolor
5       Iris-setosa       Iris-setosa
6   Iris-versicolor   Iris-versicolor
7       Iris-setosa       Iris-setosa
8   Iris-versicolor   Iris-versicolor
9   Iris-versicolor    Iris-virginica
10      Iris-setosa       Iris-setosa
11  Iris-versicolor   Iris-versicolor
12   Iris-virginica    Iris-virginica
13      Iris-setosa       Iris-setosa
14   Iris-virginica    Iris-virginica
15      Iris-setosa       Iris-setosa
16   Iris-virginica    Iris-virginica
17  Iris-versicolor   Iris-versicolor
18      Iris-setosa       Iris-setosa
19   Iris-virginica    Iris-virginica
20      Iris-setosa       Iris-setosa
21   Iris-virginica    Iris-virginica
22  Iris-versicolor   Iris-versicolor
23      Iris-setosa       Iris-setosa
24      Iris-setosa       Iris-setosa
25   Iris-virginica    Iris-virginica
26   Iris-virginica    Iris-virginica
27   Iris-virginica    Iris-virginica
28      Iris-setosa       Iris-setosa
29   Iris-virginica    Iris-virginica

In [22]:
accuracy = accuracy_score(y_test, y_predict)
print("Accuracy:", accuracy)

print("\nClassification Report: ")
print(classification_report(y_test, y_predict))

Accuracy: 0.9666666666666667

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

In [24]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_predict))

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]